[package]
name = "corona"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bcrypt = "0.14.0"
serde = { version = "1.0.162", features = ["derive"] }
toml = "0.7.3"
